import RecoilRootWrapper from "@/components/RecoilRootWrapper";
import { getMediaQueryStyle } from "@/styles/media/mediaQuery";
import { ChildNode } from "@/types/global";
import { css } from '@emotion/react';
import Head from "next/head";

import { BreakPoints } from "@/styles/media/palette";
import Header from "@/components/Header";

export default function LinearLayout({ children }: ChildNode) {
    return (
        <RecoilRootWrapper>
            <Head>
                <title>김상훈 - 프론트엔드 개발자</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main css={styles}>
                <Header />
                {children}
            </main>
        </RecoilRootWrapper>
    );
}

const styles = css`
    position: relative;
    width: 100%;
    min-height: 100vh;
    display: flex;
    flex-direction: column;
    gap: 10px;
    margin: 0 auto;
    box-sizing: border-box;
    transition: 0.2s;

    ${getMediaQueryStyle("sm", css`
        width: ${BreakPoints.sm}px;
    `)}
    
    ${getMediaQueryStyle("md", css`
        width: ${BreakPoints.md}px;
    `)}
    
    ${getMediaQueryStyle("lg", css`
        width: ${BreakPoints.lg}px;
        flex-direction: row;
    `)}
    
    ${getMediaQueryStyle("xl", css`
        width: ${BreakPoints.xl}px;
    `)}
`